src/Entity/Score.php
<?php

namespace App\Entity;

use App\Repository\ScoreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScoreRepository::class)]
class Score
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $score = null;

    #[ORM\Column(nullable: true)]
    private ?float $guess_x = null;

    #[ORM\Column(nullable: true)]
    private ?float $guess_y = null;

    #[ORM\Column(nullable: true)]
    private ?float $real_x = null;

    #[ORM\Column(nullable: true)]
    private ?float $real_y = null;

    #[ORM\ManyToOne(inversedBy: 'scores')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getGuessX(): ?float
    {
        return $this->guess_x;
    }

    public function setGuessX(?float $guess_x): self
    {
        $this->guess_x = $guess_x;

        return $this;
    }

    public function getGuessY(): ?float
    {
        return $this->guess_y;
    }

    public function setGuessY(?float $guess_y): self
    {
        $this->guess_y = $guess_y;

        return $this;
    }

    public function getRealX(): ?float
    {
        return $this->real_x;
    }

    public function setRealX(?float $real_x): self
    {
        $this->real_x = $real_x;

        return $this;
    }

    public function getRealY(): ?float
    {
        return $this->real_y;
    }

    public function setRealY(?float $real_y): self
    {
        $this->real_y = $real_y;

        return $this;
    }

    public function getGameId(): ?Game
    {
        return $this->game_id;
    }

    public function setGameId(?Game $game_id): self
    {
        $this->game_id = $game_id;

        return $this;
    }
}

src/Form/ScoreType.php
<?php

namespace App\Form;

use App\Entity\Score;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScoreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('score')
            ->add('guess_x')
            ->add('guess_y')
            ->add('real_x')
            ->add('real_y')
            ->add('game_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Score::class,
        ]);
    }
}

src/Controller/ScoreController.php
<?php

namespace App\Controller;

use App\Entity\Score;
use App\Form\ScoreType;
use App\Repository\ScoreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/score')]
class ScoreController extends AbstractController
{
    #[Route('/', name: 'app_score_index', methods: ['GET'])]
    public function index(ScoreRepository $scoreRepository): Response
    {
        return $this->render('score/index.html.twig', [
            'scores' => $scoreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_score_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ScoreRepository $scoreRepository): Response
    {
        $score = new Score();
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $scoreRepository->save($score, true);

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('score/new.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_show', methods: ['GET'])]
    public function show(Score $score): Response
    {
        return $this->render('score/show.html.twig', [
            'score' => $score,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_score_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Score $score, ScoreRepository $scoreRepository): Response
    {
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $scoreRepository->save($score, true);

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('score/edit.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_delete', methods: ['POST'])]
    public function delete(Request $request, Score $score, ScoreRepository $scoreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$score->getId(), $request->request->get('_token'))) {
            $scoreRepository->remove($score, true);
        }

        return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/score/_delete_form.html.twig
<form method="post" action="{{ path('app_score_delete', {'id': score.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ score.id) }}">
    <button class="btn">Delete</button>
</form>

templates/score/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Score{% endblock %}

{% block body %}
    <h1>Edit Score</h1>

    {{ include('score/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_score_index') }}">back to list</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}

templates/score/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score index{% endblock %}

{% block body %}
    <h1>Score index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Score</th>
                <th>Guess_x</th>
                <th>Guess_y</th>
                <th>Real_x</th>
                <th>Real_y</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for score in scores %}
            <tr>
                <td>{{ score.id }}</td>
                <td>{{ score.score }}</td>
                <td>{{ score.guessX }}</td>
                <td>{{ score.guessY }}</td>
                <td>{{ score.realX }}</td>
                <td>{{ score.realY }}</td>
                <td>
                    <a href="{{ path('app_score_show', {'id': score.id}) }}">show</a>
                    <a href="{{ path('app_score_edit', {'id': score.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_score_new') }}">Create new</a>
{% endblock %}

templates/score/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Score{% endblock %}

{% block body %}
    <h1>Create new Score</h1>

    {{ include('score/_form.html.twig') }}

    <a href="{{ path('app_score_index') }}">back to list</a>
{% endblock %}

templates/score/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score{% endblock %}

{% block body %}
    <h1>Score</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ score.id }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ score.score }}</td>
            </tr>
            <tr>
                <th>Guess_x</th>
                <td>{{ score.guessX }}</td>
            </tr>
            <tr>
                <th>Guess_y</th>
                <td>{{ score.guessY }}</td>
            </tr>
            <tr>
                <th>Real_x</th>
                <td>{{ score.realX }}</td>
            </tr>
            <tr>
                <th>Real_y</th>
                <td>{{ score.realY }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_score_index') }}">back to list</a>

    <a href="{{ path('app_score_edit', {'id': score.id}) }}">edit</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}