src/Entity/Locations.php
<?php

namespace App\Entity;

use App\Repository\LocationsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationsRepository::class)]
class Locations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $cord_x = null;

    #[ORM\Column]
    private ?float $cord_y = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCordX(): ?float
    {
        return $this->cord_x;
    }

    public function setCordX(float $cord_x): self
    {
        $this->cord_x = $cord_x;

        return $this;
    }

    public function getCordY(): ?float
    {
        return $this->cord_y;
    }

    public function setCordY(float $cord_y): self
    {
        $this->cord_y = $cord_y;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Form/LocationsType.php
<?php

namespace App\Form;

use App\Entity\Locations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cord_x')
            ->add('cord_y')
            ->add('country')
            ->add('city')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Locations::class,
        ]);
    }
}

src/Controller/LocationsController.php
<?php

namespace App\Controller;

use App\Entity\Locations;
use App\Form\LocationsType;
use App\Repository\LocationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/locations')]
class LocationsController extends AbstractController
{
    #[Route('/', name: 'app_locations_index', methods: ['GET'])]
    public function index(LocationsRepository $locationsRepository): Response
    {
        return $this->render('locations/index.html.twig', [
            'locations' => $locationsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_locations_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LocationsRepository $locationsRepository): Response
    {
        $location = new Locations();
        $form = $this->createForm(LocationsType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationsRepository->save($location, true);

            return $this->redirectToRoute('app_locations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('locations/new.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_locations_show', methods: ['GET'])]
    public function show(Locations $location): Response
    {
        return $this->render('locations/show.html.twig', [
            'location' => $location,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_locations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Locations $location, LocationsRepository $locationsRepository): Response
    {
        $form = $this->createForm(LocationsType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationsRepository->save($location, true);

            return $this->redirectToRoute('app_locations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('locations/edit.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_locations_delete', methods: ['POST'])]
    public function delete(Request $request, Locations $location, LocationsRepository $locationsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$location->getId(), $request->request->get('_token'))) {
            $locationsRepository->remove($location, true);
        }

        return $this->redirectToRoute('app_locations_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/locations/_delete_form.html.twig
<form method="post" action="{{ path('app_locations_delete', {'id': location.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ location.id) }}">
    <button class="btn">Delete</button>
</form>

templates/locations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Locations{% endblock %}

{% block body %}
    <h1>Edit Locations</h1>

    {{ include('locations/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_locations_index') }}">back to list</a>

    {{ include('locations/_delete_form.html.twig') }}
{% endblock %}

templates/locations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locations index{% endblock %}

{% block body %}
    <h1>Locations index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cord_x</th>
                <th>Cord_y</th>
                <th>Country</th>
                <th>City</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for location in locations %}
            <tr>
                <td>{{ location.id }}</td>
                <td>{{ location.cordX }}</td>
                <td>{{ location.cordY }}</td>
                <td>{{ location.country }}</td>
                <td>{{ location.city }}</td>
                <td>
                    <a href="{{ path('app_locations_show', {'id': location.id}) }}">show</a>
                    <a href="{{ path('app_locations_edit', {'id': location.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_locations_new') }}">Create new</a>
{% endblock %}

templates/locations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Locations{% endblock %}

{% block body %}
    <h1>Create new Locations</h1>

    {{ include('locations/_form.html.twig') }}

    <a href="{{ path('app_locations_index') }}">back to list</a>
{% endblock %}

templates/locations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locations{% endblock %}

{% block body %}
    <h1>Locations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ location.id }}</td>
            </tr>
            <tr>
                <th>Cord_x</th>
                <td>{{ location.cordX }}</td>
            </tr>
            <tr>
                <th>Cord_y</th>
                <td>{{ location.cordY }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ location.country }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ location.city }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_locations_index') }}">back to list</a>

    <a href="{{ path('app_locations_edit', {'id': location.id}) }}">edit</a>

    {{ include('locations/_delete_form.html.twig') }}
{% endblock %}